import { sanityClient, urlFor } from '@/sanity'
import { Collection } from '@/typings';
import { GetServerSideProps } from 'next'
import Head from 'next/head'
import Link from 'next/link';

interface Props {
  collections: Collection[];
}

export default function Home({ collections }: Props) {
  
  return (
    <div
      className='
        max-w-7xl
        mx-auto py-20 px-10
        flex flex-col
        min-h-screen
      '
    >
      <Head>
        <title>NFT Drop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1
        className='
          mb-10
          text-4xl font-extralight
        '
      >
        Mint your own <span className='font-extrabold underline decoration-pink-600/50'>mushroom</span>
      </h1>
      <main
        className='
          bg-slate-100
          shadow-xl shadow-rose-300/20
          p-10
        '
      >
        <div
          className='
            grid -space-x-3
            mg:grid-cols-2 lg:grid-cols-3 2xl:grid-cols-4
          '
        >
          {collections.map(collection => (
            <Link href={`/nft/${collection.slug.current}`}>
              <div
                className='
                  flex flex-col items-center
                  cursor-pointer
                  transition-all duration-200 hover:scale-105
                '
              >
                <img
                  src={urlFor(collection.image).url()}
                  alt={collection.collectionName}
                  className='h-96 w-60 rounded-2xl object-cover'
                />
                <div className='p-5'>
                  <h2 className='text-3xl'>{collection.title}</h2>
                  <p className='mt-2 text-sm text-gray-400'>{collection.description}</p>
                </div>
              </div>
            </Link>
          ))}
        </div>
      </main>
    </div>
  )
}

export const getServerSideProps: GetServerSideProps = async() => {
  const query = `
    *[_type == "collection"] {
      _id,
      title,
      address,
      description,
      collectionName,
      image {
        asset
      },
      previewImage {
        asset
      },
      slug {
        current
      },
      creator-> {
        _id,
        name,
        address,
        slug {
          current
        },
      },
    }
  `
  const collections = await sanityClient.fetch(query);

  return {
    props: {
      collections
    }
  }
}